# Generated by Django 4.1.1 on 2022-09-18 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EnglishApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='word',
            new_name='saved_word',
        ),
    ]
