# Generated by Django 4.1.1 on 2022-09-18 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnglishApp', '0002_rename_word_word_saved_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True, help_text='intial inserted date'),
        ),
    ]
