# Generated by Django 4.1.1 on 2022-09-18 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnglishApp', '0003_alter_word_added_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
