# Generated by Django 4.1.1 on 2022-09-18 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EnglishApp', '0004_word_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='count',
            new_name='word_count',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='value',
            new_name='word_value',
        ),
    ]
